language: minimal

git:
  depth: 1

env:
  global:
  - PROG_VER=$(head -n 1 VERSION.txt)

matrix:
  include:

    - os: windows
      language: shell
      before_install:
      - wget https://bitbucket.org/mitrich_k/inno-download-plugin/downloads/idpsetup-1.5.1.exe
      install:
      - choco install innosetup --version=5.6.1 -y
      - echo "idpsetup-1.5.1.exe /VERYSILENT" > sdfa.bat
      - ./sdfa.bat
      - choco install lazarus make -y
      script:
      - ls /c/lazarus/fpc/
      - export LAZARUS_DIR="c:\lazarus"
      - export PATH=/c/lazarus/fpc/3.0.4/bin:$PATH
      - /c/lazarus/lazbuild -B transgui.lpi
      - make clean
      - make all
      - ls Release/

notifications:
  email:
    on_failure: never
