language: minimal

git:
  depth: 1

env:
  global:
  - PROG_VER=$(head -n 1 VERSION.txt)

matrix:
  include:

    - os: windows
      language: shell
      before_install:
      - wget https://bitbucket.org/mitrich_k/inno-download-plugin/downloads/idpsetup-1.5.1.exe
      install:
      - choco install innosetup --version=5.6.1 -y
      - choco install lazarus make -y
      - ./idpsetup-1.5.1.exe /VERYSILENT
      script:
      - cd setup/win
      - make_setup.bat  c:\lazarus\ "c:\Program Files (x86)\Inno Setup 5\"
      - ls Release/

notifications:
  email:
    on_failure: never
