language: minimal

git:
  depth: 1

env:
  global:
  - PROG_VER=$(head -n 1 VERSION.txt)

matrix:
  include:

    - os: windows
      language: shell
      install:
      - choco install innosetup --version=5.6.1 -y
      - choco install lazarus inno-download-plugin -y
      - ls /c/lazarus/fpc/
      - export LAZARUS_DIR="c:\lazarus"
      script:
      - cd setup/win
      - ./install_deps.bat
      - ./make_setup.bat
      - ls Release/

notifications:
  email:
    on_failure: never
